### ISSUE TITLE
Couldn't load plugin on dev version

### ISSUE THREAD

**Issue by Suncatcher** [henrypp/chromium#62]
Doesn't load PDF files inline on Version 79.0.3917.0 (Official Build) (64-bit).

![Annotation 2019-10-06 230730](https://user-images.githubusercontent.com/6388034/66284689-9f78b980-e88e-11e9-8d93-385ec3ca4e23.jpg)

Don't know if this is a launcher issue or Chromium issue, just in case I posted issue in [their bugtracker too](https://bugs.chromium.org/p/chromium/issues/detail?id=1010997&can=4&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified).

**Comment by woolyss** [comment]
Hello @Suncatcher Suncatcher
You use a snapshot of Chromium. This build is really just development tool for checking whether issues are fixed in the latest Chromium code. It can be buggy and unstable. The  Version 79.0.3917.0 has many [revisions](https://chromium.googlesource.com/chromium/src/+log/79.0.3917.0). So difficult to help you.
If you want to use a better version of Chromium, prefer a stable one.

**Comment by Suncatcher** [comment]
No, read the chrome bugtracker thread thoroughly

Version 79.0.3917.0 (Official Build) (64-bit) - not working.
Version 79.0.3935.0 (Developer Build) (64-bit) - working.

Developer build with more recent build is working, stable - no

**Comment by Suncatcher** [comment]
Fixed on 80.0.3946.0 dev version
